<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Lokasi_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    function add_lokasi($params)
    {
        $this->db->insert('lokasi',$params);
        return $this->db->insert_id();
    }

    function get_all_lokasi()
    {
        $lokasi = $this->db->query("
            SELECT
                *

            FROM
                `lokasi`

            WHERE
                1 = 1            
        ")->result_array();

        return $lokasi;
    }

    function get_lokasi($lokasi_id)
    {
        $lokasi = $this->db->query("
            SELECT
                *

            FROM
                `lokasi`
            
            WHERE
                `lokasi_id` = ?

        ",array($lokasi_id))->row_array();

        return $lokasi;
    }

    function update_lokasi($lokasi_id,$params)
    {
        $this->db->where('lokasi_id',$lokasi_id);
        return $this->db->update('lokasi',$params);
    }

    function delete_lokasi($lokasi_id)
    {
        return $this->db->delete('lokasi',array('lokasi_id'=>$lokasi_id));
    }
}
