<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get user by usr_id
     */
    function get_user($usr_id)
    {
        $user = $this->db->query("
            SELECT
                u.*, g.gro_name

            FROM
                `ms_user` u
            LEFT JOIN groups g
            on u.usr_group = g.gro_id

            WHERE
                `user_id` = ?

        ",array($usr_id))->row_array();

        return $user;
    }

        
    /*
     * Get all users
     */
    function get_all_users()
    {
        $users = $this->db->query("
            SELECT
                *

            FROM
                `ms_user`
            WHERE
                user_id != 1

            ORDER BY `user_id` DESC
        ")->result_array();

        return $users;
    }
    
    function add_user($params)
    {
        $this->db->insert('ms_user',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update user
     */
    function update_user($usr_id,$params)
    {
        $this->db->where('user_id',$usr_id);
        return $this->db->update('ms_user',$params);
    }
    
    /*
     * function to delete user
     */
    function delete_user($usr_id)
    {
        return $this->db->delete('ms_user',array('user_id'=>$usr_id));
    }
}
