<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Background_surat extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        
        $this->load->model('general_model');
        
        $count = $this->db->query("SELECT COUNT(1) as count FROM company
        WHERE LOWER(company_name) = LOWER('PT. TEMPO REALTY')")->row();						
        
        if($count->count <= 0){
            $this->session->set_flashdata('error','Invalid Serial Number');    
            redirect('login');  
        }

        if($this->session->userdata('is_login') !=  true)
        {
            $this->session->set_flashdata('error','You have no access to that page.');
            redirect('login');  
        }       
    } 

    /*
     * Listing of users
     */
    function index()
    {        
        $this->user_library->checking_page_access('background',"background","view");                               

        $sorting['field'] = "day";
        $sorting['sort'] = "asc";
        $data['background_surat'] = $this->general_model->get_info("*", "background_surat", array(), $sorting);                
        $this->load->view('backend/background_surat/master_background_surat',$data);
    }
   
    function edit($background_surat_id)
    {           
        $this->user_library->checking_page_access('background',"background","edit");           
        date_default_timezone_set('Asia/Jakarta');            
		
        $where_background['background_surat_id'] = $background_surat_id;   
        $data['background'] = $this->general_model->get_info("*", "background_surat", $where_background);
        
        if($data['background'] != FALSE)
        {        
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
                    'background_color_declaration_form' => $this->input->post('background_color_declaration_form'),   
                    'background_color_safe_entry_pass' => $this->input->post('background_color_safe_entry_pass'),   
                    'updated_by' => $this->session->userdata('user_id'),             
                    'updated_at' => date('Y-m-d H:i:s'),                 
                );            

                $where_background['background_surat_id'] = $background_surat_id;  

                $this->db->update('background_surat',$params, $where_background);         

            $this->session->set_flashdata('success','Edit Background Success');    
            redirect('admin/background_surat');
            }
            else
            {                                
                $this->load->view('backend/background_surat/edit_background_surat',$data);
            }
        }
        else {
            $this->session->set_flashdata('error','Background Setting doesnt exist');    
            redirect('admin/background_surat');
        }        
    } 
    
}
