<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Change_password extends CI_Controller{
    function __construct()
    {
        parent::__construct();

        $count = $this->db->query("SELECT COUNT(1) as count FROM company
        WHERE LOWER(company_name) = LOWER('PT. TEMPO REALTY')")->row();						
        
        if($count->count <= 0){
            $this->session->set_flashdata('error','Invalid Serial Number');    
            redirect('login');  
        }

        if($this->session->userdata('is_login') !=  true)
        {
            $this->session->set_flashdata('error','You have no access to that page.');
            redirect('login');  
        }
        $this->load->model('Lokasi_model');
        $this->load->model('general_model');        
    } 

    /*
     * Listing of users
     */
    function index()
    {                
        if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
                    'password' => sha1($this->input->post('password')),                       
                );            

                $where_user['user_id'] = $this->session->userdata('user_id');  

                $this->db->update('ms_user',$params, $where_user);         

            $this->session->set_flashdata('success','Change Password Success');    

            $this->load->view('backend/change_password/change_password');
            }
            else
            {                                
                $this->load->view('backend/change_password/change_password');
            }        
    }            
}
