<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Declaration_form extends CI_Controller{
    function __construct()
    {
        parent::__construct();

        $count = $this->db->query("SELECT COUNT(1) as count FROM company
        WHERE LOWER(company_name) = LOWER('PT. TEMPO REALTY')")->row();						
        
        if($count->count <= 0){
            $this->session->set_flashdata('error','Invalid Serial Number');    
            redirect('login');  
        }
        
        if($this->session->userdata('is_login') !=  true || $this->user_library->show_declaration_form_access() != 1)
        {
            $this->session->set_flashdata('error','You have no access to that page.');
            redirect('login');  
        }        

        $this->load->model('general_model');        
    } 

    /*
     * Listing of users
     */
    function index()
    {
        $exception['field'] = 'status';
        $exception['value'] = 3;
        
        $data['surat'] = $this->general_model->get_info("*", "surat_pernyataan", array(), array(), array(),
        $exception);        
        $this->load->view('backend/declaration_form/master_declaration_form',$data);
    }            

    public function View($id){
        $where_surat['surat_pernyataan_id'] = $id;        										
        $data['me'] = $this->general_model->get_info("*", "surat_pernyataan", $where_surat);  
        if($data['me'] != FALSE) { 
            $this->load->view('backend/declaration_form/view_declaration_form',$data);
        }else{
            $this->session->set_flashdata('error','Declaration Form doesnt exist');    
            redirect('admin/declaration_form');
        }		
    }    
}
