<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Report_occupancy extends CI_Controller{
    function __construct()
    {
        parent::__construct();        
        $this->load->model('report_model');        
    } 

    /*
     * Listing of users
     */
    function index()
    {        
        if($this->session->userdata('is_login') !=  true || $this->user_library->show_report_access() != 1)
        {
            $this->session->set_flashdata('error','You have no access to that page.');
            redirect('login');  
        }

        $count = $this->db->query("SELECT COUNT(1) as count FROM company
        WHERE LOWER(company_name) = LOWER('PT. TEMPO REALTY')")->row();						
        
        if($count->count <= 0){
            $this->session->set_flashdata('error','Invalid Serial Number');    
            redirect('login');  
        }
        
        $this->load->view('backend/report/master_report_occupancy');
    }    

    public function get_data()
	{			                        
        $newdata = array(
            'SEARCH_PERIOD_REPORT_OCCUPANCY' => $this->input->post("period"),            
        );
        $this->session->set_userdata($newdata);

        $search_date = $this->input->post("period");

        $start_date = "";
        $end_date = "";
        if($search_date != ""){
            $daterange_exploded = preg_split('@-@', $search_date, NULL, PREG_SPLIT_NO_EMPTY);
            if(count($daterange_exploded) > 0){
                $start_date_reformat = preg_split('@/@',trim($daterange_exploded[0]," "), NULL, PREG_SPLIT_NO_EMPTY);
                $start_date_format = $start_date_reformat[2]."-".$start_date_reformat[1]."-".$start_date_reformat[0];
                $end_date_reformat = preg_split('@/@',trim($daterange_exploded[1]," "), NULL, PREG_SPLIT_NO_EMPTY);
                $end_date_format = $end_date_reformat[2]."-".$end_date_reformat[1]."-".$end_date_reformat[0];
                
                $start_date = date("Y-m-d", strtotime($start_date_format));
                $end_date = date("Y-m-d", strtotime($end_date_format));
            }
            
        }else{
            $start_date = date('Y-m-01');
            $end_date = date('Y-m-t');
        }               
        
        $html = '<a style="font-family:montserrat;margin-bottom:1%;margin-top:2%;margin-left:2%" class="btn btn-success btn-labeled fa fa-file-excel-o" onclick="location.href=\''.site_url('admin/report_occupancy/export_excel').'\'">GENERATE EXCEL</a>';
        $html .= '<div class="table-responsive">';
        $html .= '<table id="report" class="table table-striped table-bordered" cellspacing="0" width="100%">';
        $html .= '<thead style="font-size:1em">';
        $html .= '<tr style="background: #455a64; color:white">';
        $html .= '<th style="text-align:center;vertical-align:middle">Tanggal</th>';
        $html .= '<th style="text-align:center;vertical-align:middle">Waktu</th>';
        $html .= '<th style="text-align:center;vertical-align:middle">IN</th>';
        $html .= '<th style="text-align:center;vertical-align:middle">OUT</th>';
        $html .= '<th style="text-align:center;vertical-align:middle">OCCUPANCY</th>';        
        $html .= '</tr>';
        $html .= '</thead>';
        $html .= '<tbody>';                 

        $fix_end_date = new DateTime($end_date);

        $daterange = new DatePeriod(new DateTime($start_date), new DateInterval('P1D'), $fix_end_date->modify( '+1 day' ));

        $dowMap = array('07.00-07:59', '08.00-08:59', '09.00-09:59', '10.00-10:59', 
        '11.00-11:59', '12.00-12:59', '13.00-13:59','14.00-14:59', '15.00-15:59', 
        '16.00-16:59', '17.00-17:59', '18.00-18:59');		                

        foreach($daterange as $date){            

            $report = $this->report_model->get_report_occupancy($date->format("Y-m-d"));                                    

            $occupancy = 0;            

            if($report != false){                                                
                for ($x = 1; $x <= count($dowMap); $x++) {                                                                                
                    $occupancy = $occupancy+$report[$x*2-1]-$report[$x*2];

                    $html .= '<tr style="font-size:1.1em; text-align:center">';
                    $html .= '<td style="vertical-align:middle">'.$date->format("Y-m-d").'</td>';
                    $html .= '<td style="vertical-align:middle">'.$dowMap[$x-1].'</td>';                        
                    $html .= '<td style="vertical-align:middle">'.$report[$x*2-1].'</td>';                    
                    $html .= '<td style="vertical-align:middle">'.$report[$x*2].'</td>';                                        
                    $html .= '<td style="vertical-align:middle">'.$occupancy.'</td>';                    
                    $html .= '</tr>';                                        
                }
            }                            
        }
                            
        $html .= '</tbody>';
        $html .= '</table>';
        $html .= '</div>';

        echo json_encode($html);		
    }

    public function export_excel(){
        $status = TRUE;
        $data['search_period'] = $this->session->userdata('SEARCH_PERIOD_REPORT_OCCUPANCY');        

        $search_date = $data['search_period'];

        $start_date = "";
        $end_date = "";
        if($search_date != ""){
            $daterange_exploded = preg_split('@-@', $search_date, NULL, PREG_SPLIT_NO_EMPTY);
            if(count($daterange_exploded) > 0){
                $start_date_reformat = preg_split('@/@',trim($daterange_exploded[0]," "), NULL, PREG_SPLIT_NO_EMPTY);
                $start_date_format = $start_date_reformat[2]."-".$start_date_reformat[1]."-".$start_date_reformat[0];
                $end_date_reformat = preg_split('@/@',trim($daterange_exploded[1]," "), NULL, PREG_SPLIT_NO_EMPTY);
                $end_date_format = $end_date_reformat[2]."-".$end_date_reformat[1]."-".$end_date_reformat[0];
                
                $start_date = date("Y-m-d", strtotime($start_date_format));
                $end_date = date("Y-m-d", strtotime($end_date_format));
            }
            
        }else{
            $start_date = date('Y-m-01');
            $end_date = date('Y-m-t');
        }               
        
        $fix_end_date = new DateTime($end_date);

        $daterange = new DatePeriod(new DateTime($start_date), new DateInterval('P1D'), $fix_end_date->modify( '+1 day' ));

        $dowMap = array('07.00-07:59', '08.00-08:59', '09.00-09:59', '10.00-10:59', 
        '11.00-11:59', '12.00-12:59', '13.00-13:59','14.00-14:59', '15.00-15:59', 
        '16.00-16:59', '17.00-17:59', '18.00-18:59');	
        
        $html = "";

        foreach($daterange as $date){            

            $report = $this->report_model->get_report_occupancy($date->format("Y-m-d"));                                    

            $occupancy = 0;            

            if($report != false){                                                
                for ($x = 1; $x <= count($dowMap); $x++) {                                                                                
                    $occupancy = $occupancy+$report[$x*2-1]-$report[$x*2];

                    $html .= '<tr>';
                    $html .= '<td class="str" style="text-align:center">'.$date->format("Y-m-d").'</td>';
                    $html .= '<td class="str" style="text-align:center">'.$dowMap[$x-1].'</td>';                        
                    $html .= '<td class="str" style="text-align:center">'.$report[$x*2-1].'</td>';                    
                    $html .= '<td class="str" style="text-align:center">'.$report[$x*2].'</td>';                                        
                    $html .= '<td class="str" style="text-align:center">'.$occupancy.'</td>';                    
                    $html .= '</tr>';                                        
                }
            }                            
        }

        $data["value"] = $html;
                    
        if($status == TRUE){
            $this->load->view('backend/report/report_occupancy_export_excel',$data);
        }else{
            redirect('report');
        }
    }
}
