<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Report extends CI_Controller{
    function __construct()
    {
        parent::__construct();        
        $this->load->model('report_model');        
    } 

    /*
     * Listing of users
     */
    function index()
    {        
        if($this->session->userdata('is_login') !=  true || $this->user_library->show_report_access() != 1)
        {
            $this->session->set_flashdata('error','You have no access to that page.');
            redirect('login');  
        }

        $count = $this->db->query("SELECT COUNT(1) as count FROM company
        WHERE LOWER(company_name) = LOWER('PT. TEMPO REALTY')")->row();						
        
        if($count->count <= 0){
            $this->session->set_flashdata('error','Invalid Serial Number');    
            redirect('login');  
        }
        
        $this->load->view('backend/report/master_report');
    }
    
    public function get_data()
	{			                        
        $newdata = array(
            'SEARCH_PERIOD_REPORT' => $this->input->post("period"),            
        );
        $this->session->set_userdata($newdata);

        $report = $this->report_model->get_report();	
        
        $html = '<a style="font-family:montserrat;margin-bottom:1%;margin-top:2%;margin-left:2%" class="btn btn-success btn-labeled fa fa-file-excel-o" onclick="location.href=\''.site_url('admin/report/export_excel').'\'">GENERATE EXCEL</a>';
        $html .= '<div class="table-responsive">';
        $html .= '<table id="report" class="table table-striped table-bordered" cellspacing="0" width="100%">';
        $html .= '<thead style="font-size:1em">';
        $html .= '<tr style="background: #455a64; color:white">';
        $html .= '<th style="text-align:center;vertical-align:middle">Nomor Handphone</th>';
        $html .= '<th style="text-align:center;vertical-align:middle">Nama Lengkap</th>';
        $html .= '<th style="text-align:center;vertical-align:middle">Official ID Number</th>';
        $html .= '<th style="text-align:center;vertical-align:middle">Email Address</th>';
        $html .= '<th style="text-align:center;vertical-align:middle">Registration Number</th>';
        $html .= '<th style="text-align:center;vertical-align:middle">Tanggal Surat Pernyataan</th>';
        $html .= '<th style="text-align:center;vertical-align:middle">Tanggal Checkin</th>';        
        $html .= '<th style="text-align:center;vertical-align:middle">Jam Checkin</th>';
        $html .= '<th style="text-align:center;vertical-align:middle">Tanggal CheckOut</th>';
        $html .= '<th style="text-align:center;vertical-align:middle">Jam CheckOut</th>';
        $html .= '<th style="text-align:center;vertical-align:middle">Type Checkoout</th>';
        $html .= '<th style="text-align:center;vertical-align:middle">ID Number Input Type</th>';
        $html .= '<th style="text-align:center;vertical-align:middle">Checkin Point</th>';
        $html .= '</tr>';
        $html .= '</thead>';
        $html .= '<tbody>';                                      
        if($report != FALSE){
            foreach($report as $row){
                $html .= '<tr style="font-size:1.1em; text-align:center">';  
                $html .= '<td style="vertical-align:middle">'.$row->phone_number.'</td>';
                $html .= '<td style="vertical-align:middle">'.$row->name.'</td>';                                
                $html .= '<td style="vertical-align:middle">'.$row->official_id_number.'</td>';
                $html .= '<td style="vertical-align:middle">'.$row->email.'</td>';                                
                $html .= '<td style="vertical-align:middle">'.$row->registration_number.'</td>';
                if($row->created_on != ""){
                    $html .= '<td style="vertical-align:middle">'.date_format(date_create($row->created_on),"j F Y").'</td>';                                
                }else{
                    $html .= '<td style="vertical-align:middle"></td>';                                
                }                
                $html .= '<td style="vertical-align:middle">'.date_format(date_create($row->check_in),"j F Y").'</td>';                                
                if(date("H", strtotime($row->check_in)) == "00"){
                    $html .= '<td style="vertical-align:middle">'.date('H:i A', strtotime($row->check_in)).'</td>';                                                    
                }else{
                    $html .= '<td style="vertical-align:middle">'.date('h:i A', strtotime($row->check_in)).'</td>';                                                                        
                }					

                if($row->check_out != ""){
                    $html .= '<td style="vertical-align:middle">'.date_format(date_create($row->check_out),"j F Y").'</td>';                                
                    if(date("H", strtotime($row->check_out)) == "00"){
                        $html .= '<td style="vertical-align:middle">'.date('H:i A', strtotime($row->check_out)).'</td>';                                                    
                    }else{
                        $html .= '<td style="vertical-align:middle">'.date('h:i A', strtotime($row->check_out)).'</td>';                                                                        
                    }					
                }else{
                    $html .= '<td style="vertical-align:middle"></td>';                                                                        
                    $html .= '<td style="vertical-align:middle"></td>';                                                                        
                }

                $type_checkout = "Auto checkout";
                if($row->type_checkout == 1 || $row->type_checkout == 3){
                    $type_checkout = "Self checkout";
                }

                $html .= '<td style="vertical-align:middle">'.$type_checkout.'</td>';    
                
                $description_input = "N/A";
                                      if($row->type_id_card != 0 && $row->official_id_number != ""){
                                        if($row->type_input_official_id_number == 1){
                                          $description_input = "OCR Recognition";
                                        }else if($row->type_input_official_id_number == 2){
                                          $description_input = "Manual Input";                                
                                        }else if($row->type_input_official_id_number == 3){
                                          $description_input = "OCR Corrected By Receptionist";                                
                                        }
                                      }

                $html .= '<td style="vertical-align:middle">'.$description_input.'</td>';                                
                $html .= '<td style="vertical-align:middle">'.$row->nama_lokasi.'</td>';                                
                $html .= '</tr>';   
            }
        }else{
            $html .= '<tr>';
            $html .= '<td colspan="13" class="text-center">No Data Available</td>';
            $html .= '</tr>';
        }             
        $html .= '</tbody>';
        $html .= '</table>';
        $html .= '</div>';

        echo json_encode($html);		
    }    

    public function export_excel(){
        $status = TRUE;
        $data['search_period'] = $this->session->userdata('SEARCH_PERIOD_REPORT');        
        
        $data['report_list'] = $this->report_model->get_report();
                    
        if($status == TRUE){
            $this->load->view('backend/report/report_export_excel',$data);
        }else{
            redirect('report');
        }
    }
}
