<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Visitor_in_building extends CI_Controller{
    function __construct()
    {
        parent::__construct();        

        $this->load->model('general_model');        
    } 

    /*
     * Listing of users
     */
    function index()
    {        
        $count = $this->db->query("SELECT COUNT(1) as count FROM company
        WHERE LOWER(company_name) = LOWER('PT. TEMPO REALTY')")->row();						
        
        if($count->count <= 0){
            $this->session->set_flashdata('error','Invalid Serial Number');    
            redirect('login');  
        }
        
        if($this->session->userdata('is_login') !=  true || $this->user_library->show_visitor_in_building_access() != 1)
        {
            $this->session->set_flashdata('error','You have no access to that page.');
            redirect('login');  
        } 

        $this->load->view('backend/visitor_in_building/master_visitor_in_building');
    }     
    
    function get_data(){    
        date_default_timezone_set('Asia/Jakarta');

        $this->db->select("r.*, sp.type_id_card, sp.type_input_official_id_number, 
        sp.email, sp.official_id_number, DATE_FORMAT(sp.created_on, '%e %M  %Y ') as created_on, 
        sp.name, l.nama_lokasi, DATE_FORMAT(r.check_in, '%e %M %Y ') as check_in_date, 
        DATE_FORMAT(r.check_in, '%H:%i:%S ') as check_in_hours");
        $this->db->join("surat_pernyataan sp","r.surat_pernyataan_id = sp.surat_pernyataan_id","left");                
        $this->db->join("lokasi l","l.lokasi_id = r.location_checkin","left");                
        $this->db->where("r.is_submit = 1 AND r.is_checkout = 0 AND r.check_out > '".date('Y-m-d H:i:s')."'");        
        $this->db->order_by("r.check_in", "ASC");

        $visitor_in_building = $this->db->get("registration r")->result_array();        
                
$callback = array(        
    "iTotalRecords" => count($visitor_in_building),    
    'iTotalDisplayRecords'=>count($visitor_in_building),    
    'data'=>$visitor_in_building
);
header('Content-Type: application/json');
echo json_encode($callback); // Convert array $callback ke json

    }
}
